### ISSUE TITLE
Getting all the data from chain.json

### ISSUE THREAD

**Issue by sunnya97** [ovrclk/cosmos-omnibus#97]
Just a question, cause I'm not too familiar with Docker deployments, so sorry if this doesn't make sense.  But it seems each chain's Docker files have some data hardcoded in the Docker file.  It seems this is primarily the git repo/version, link to genesis file, name of home directory, and gas prices.  However, it seems that all of this data is available in the chain.json, so is there a reason to not only pass in the chain.json as the only input?

**Comment by boz** [comment]
We can start optionally using `chain.json` at build time to set defaults, not a bad idea.

You can use [`chain.json`](https://github.com/ovrclk/cosmos-omnibus/blob/e1e810ea899faa4cd72357d5e57a751e55732762/run.sh#L13-L19) for configuration at runtime - but it doesn't look like we're pulling gas prices at the moment.  Runtime configuration can also be set manually via environment variables or flags.

**Comment by tombeynon** [comment]
We can definitely pull more runtime config from chain.json, does it make sense to use `fixed_min_gas_price` if available for the `minimum_gas_price`? Would be great to automate that particular config since Osmosis will require it soon.

_Buiild_ time config is something I've thought about making entirely dynamic from chain.json but I think it breaks the Docker convention of repeatable builds - it would be very easy for a chain to be accidentally upgraded/downgraded when a new version of Omnibus is released for example. I was thinking a Makefile/CLI tool for Omnibus might be a good idea though - it could automate the addition/update of chains using a chain.json, which would update the `[build.yml](https://github.com/ovrclk/cosmos-omnibus/blob/master/gravitybridge/build.yml#L8-L12)` files with the correct version, binary URL etc. 

I'd love to get to a place where changes to the Chain Registry can automatically trigger updates in Omnibus, probably with a PR review in the middle.

**Comment by tombeynon** [comment]
Fixed in #154 and #162
